spring.application.name=FadeApp
spring.datasource.url=jdbc:postgresql://localhost:5432/fadeapp
spring.datasource.username=fadeapp
spring.datasource.password=local-dev-password

spring.jpa.hibernate.ddl-auto=update
logging.file.name=fadeapp.log